name: Drive Web CD
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_MACHINE_PRIVATE_KEY }}
          known_hosts: 'undetermined-yet'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_MACHINE_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Run Deploy Script
        run: "ssh -t ${{ secrets.PRODUCTION_MACHINE_USER }}@${{ secrets.PRODUCTION_MACHINE_HOSTNAME }} './deploy-web.sh'"
