name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slash_command_dispatch:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'deployed') || contains(github.event.issue.labels.*.name, 'preview') }}
    steps:
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: update-preview,check-preview
          permission: write
          repository: internxt/environments
          issue-type: pull-request
          allow-edits: false
          reactions: false
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            
            > [!CAUTION]
            > Couldn't dispatch your command due to error:
            > **${{ steps.scd.outputs.error-message }}**